#include <Wire.h>
#include <Arduino_MKRENV.h>
#include <SPI.h>
#include <SD.h>
#include <MKRWAN.h>
#include <Adafruit_BMP280.h>
#include "ArduinoLowPower.h"
#include "TinyGPS++.h"
#include "io.h"
#include "vars.h"
#include "int.h"
#include "wtr.h"
#include "atm.h"
